### ISSUE TITLE
Empty output in v2.5.0

### ISSUE THREAD

**Issue by ValeriiVasin** [jasmine/jasmine-npm#90] opened 2016-09-02 10:20 UTC
Today we've got the new version and now after we run our tests (from `./node_modules/.bin/jasmine`) we do see empty output. Prob. config not found or so. For config we are using `spec/support/jasmine.json`

Is there any breaking changes in released version?

**Comment by EnKrypt** [comment] 2016-09-02 11:24
I'm having the same problem. I don't see any output at all.

I thought I messed up by trying to run the command line executable from a local install, so I tried it again by installing it with the global flag in an empty project, but there's been no difference. Output is literally blank, see image below :

![jasmine console](https://i.imgur.com/CndWuOm.png)

Also, @ValeriiVasin, would you mind changing the title of the issue to something more specific so that others looking up this issue can come here as well?

**Comment by ValeriiVasin** [comment] 2016-09-02 12:29
@EnKrypt changed to problems with v2.5.0, not sure what it exactly is :)

**Comment by EnKrypt** [comment] 2016-09-02 15:22
How about something along the lines of 'No output/empty output/nothing displayed in v2.5.0'? That is similar to what I googled for before coming here.

**Comment by ValeriiVasin** [comment] 2016-09-02 15:31
@EnKrypt changed it

**Comment by agirorn** [comment] 2016-09-02 23:26
Is this not a duplicate of #88 and is fixed in #89 and the only thing that is left is to publish a new version to fix this for everyone?

**Comment by EnKrypt** [comment] 2016-09-03 02:56
@agirorn Yes it looks like it. That pull request has been merged less then a day ago, so anyone who does get this particular version of jasmine from npm should probably be fine,

**Comment by bcaudan** [comment] 2016-09-03 10:21
It is not fixed by #89. It can be reproduced on this repository tests by [using the default reporter](https://github.com/jasmine/jasmine-npm/issues/91).

You can compare travis log [without the default reporter](https://travis-ci.org/jasmine/jasmine-npm/jobs/156999002) and [with it](https://travis-ci.org/jasmine/jasmine-npm/jobs/157286567).

**Comment by nashwaan** [comment] 2016-09-06 14:36
Does this mean the default reporter 'consoleReporter' is not used anymore? Is it replaced with 'exitCodeReported'?
If this is the case, then how to manually set 'consoleReporter' as the current reporter?

**Comment by slackersoft** [comment] 2016-09-07 22:21
Closing this as a duplicate of #88. The fix should be released in v2.5.1

**Closed by slackersoft** 2016-09-07 22:21 UTC

**Comment by Liero** [comment] 2016-09-08 07:47
I have installed 2.5.1 and still no output:

```
C:\Temp\jasminetest>npm install jasmine@2.5.1 --global
C:\Users\username\AppData\Roaming\npm\jasmine -> C:\Users\username\AppData\Roaming\npm\node_modules\jasmine\bin\jasmine.js
C:\Users\username\AppData\Roaming\npm
`-- jasmine@2.5.1


C:\Temp\jasminetest>jasmine init

C:\Temp\jasminetest>jasmine examples

C:\Temp\jasminetest>jasmine

C:\Temp\jasminetest>jasmine -v
jasmine v2.5.1
jasmine-core v2.5.1
```

**Comment by EnKrypt** [comment] 2016-09-08 11:00
@slackersoft : I disapprove of your moderation disciplines.

Issues should never be closed because "there will be a fix soon". They should remain open to foster further discussion and more importantly: to verify that a solution actually exists before marking the issue as resolved.

**Comment by slackersoft** [comment] 2016-09-08 14:04
@EnKrypt it's still a dupe, and 2.5.1 was released with what I thought was the six at the time.
