### ISSUE TITLE
Memory leak when using Jasmine programatically

### ISSUE THREAD

**Issue by nicojs** [jasmine/jasmine-npm#134] opened 2018-07-07 00:41 UTC
Hi  :wave:, thanks for creating Jasmine. 

When using Jasmine programmatically there is a memory leak. Every time `jasmine.execute` is called, a [new listener is added to the process](https://github.com/jasmine/jasmine-npm/blob/1f60cbcf784381a7a743678a8e3cb67f8d6fe24e/lib/jasmine.js#L184). This eventually leads to this warning in node: ` MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit`

Why is the listener there? It is a curious side effect.

**Comment by slackersoft** [comment] 2018-08-01 00:59
Jasmine adds a listener to exit in order to ensure the suite has finished executing when the process exits. This way if a spec accidentally calls the real `process.exit()` the Jasmine process will at least set a non-0 exit code to indicate the failure to complete the suite (See jasmine/jasmine#1273).

It also looks like this is a duplicate of #125 which is a PR to fix this issue. It looks like it has languished a bit, so I would also be happy to review a pull request to make sure to `process.removeListener` when `checkExit` is called to ensure Jasmine is cleaning up after itself.

**Closed** 2019-01-31 01:52 UTC
