### ISSUE TITLE
done stops working if code is placed before it

### ISSUE THREAD

**Issue by wiseguy12851** [jasmine/jasmine-npm#62] opened 2015-12-10 22:12 UTC
I have a test case which tests a promise being called, if it does get called it tests the returned value is correct. However I've noticed that Jasmine works just fine as long as I call done inside the promise `then` function but if I do any checking of the returned value, any loops, or even just a single 1 line `expect` done stops working.

What I mean by stops working is done is clearly there still, its accessible inside the function and its perfectly callable, but calling it doesn't do anything. In fact if I do place `expect` calls before done they don't flag an error if wrong. Non-jasmine code works just fine but its like any jasmine code or jasmine functions just mysteriously stop working without any kind of error

Eventually jasmine times out with async timeout, once timed out, again, no errors are listed it just acs like done is never called.

However if I comment out all code except for  `done` then everything works as expected.

**Comment by slackersoft** [comment] 2015-12-10 22:26
Do you have a simple example of a test suite causing this issue? Jasmine has plenty of tests and other suites that should be doing what I think you're explaining, so it should work.

Also, what version of jasmine are you using (`jasmine -v` should tell you both npm and core versions).

Thanks

**Comment by wiseguy12851** [comment] 2015-12-11 01:01
Sorry forgot to mention the version:

Jasmine version 2.4.1
Node version 5.1.1

The project is on github and the link to the full spec file is here https://github.com/RussellsToolbox/isomorphic-cypher/blob/dev/spec/spec.js .

Near the end this is the test I'm having problems with
```javascript
it("2 valid queries once", function(done)
{
    this.inst.shelfQuery([{
        name: "test1",
        query: 'return "test1"'
    },{
        name: "test2",
        query: 'return "test2"'
    }]);

    var resultObj = this.inst.unshelfQuery([
        "test1",
        "test2"
    ]);

    this.inst.unshelfQuery([
        "test1",
        "test2"
    ]).then(function(resultObj)
    {
        expect(Array.isArray(resultObjs)).toEqual(true);

        for(var i = 0; i < resultObjs.length; i++)
        {
            var resultObj = resultObjs[i];
            expect(resultObj.firstValue).toEqual("test" + (i+1));
            expect(resultObj.queryObj.query).toEqual('return "test' + (i+1) + '"');
        }

        done();
    });
});
```

it fails with this message:

```
1) class unshelfQuery 2 valid queries once
  Message:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at Timer.listOnTimeout (timers.js:92:15)
```

As mentioned above, all jasmine code doesn't do anything inside the promise, only non-jasmine code. The only way to get it to work is to remove all code except for done in which case it works just fine. Further example below:

```javascript
it("2 valid queries once", function(done)
{
    this.inst.shelfQuery([{
        name: "test1",
        query: 'return "test1"'
    },{
        name: "test2",
        query: 'return "test2"'
    }]);

    var resultObj = this.inst.unshelfQuery([
        "test1",
        "test2"
    ]);

    this.inst.unshelfQuery([
        "test1",
        "test2"
    ]).then(function(resultObj)
    {
        // This will work as expected
        done();
    });
});
```

But having even a single line of code before done will cause the issues again.

**Comment by amavisca** [comment] 2016-01-08 04:06
Did you find a fix to your issue? I downloaded your repo and setup a default neo4j database and `npm test` runs successfully now.

**Comment by amavisca** [comment] 2016-01-22 03:56
I couldn't reproduce this so I'm going to go ahead and close the issue. If you're still having a problem feel free to open it back up again.

Thanks!

**Closed by amavisca** 2016-01-22 03:56 UTC

**Comment by simon-o-matic** [comment] 2016-03-03 10:17
Same thing happens to me. On older versions  (Jjsmine-node 1.14.3, node v4.2.1)

```
it("provision with illegal bucket name", function(done) {
		lambda.invoke(provisionLambda, JSON.stringify({"bucketName": "3S349'"})).then(function(data) {
			console.log("here again" + JSON.stringify(data));
			done(); // test past
			expect(data.Payload.errorMessage.code).toBe("InvalidBucketName");
			// done(); // done here causes a timeout error on the test
		}, function(err) {
			console.log("not here!");
			fail();
			done();
		});
	}, 10000);
```

I might try upgrading everything and seeing what happens.

**Comment by simon-o-matic** [comment] 2016-03-03 12:39
Ok, I've solve the problem and I expect you have the same issue @wiseguy12851. I didn't have a final catch after the then() so my code was failing before the done() (```errorMessage``` was ```undefined```) but I just didn't know it because it failed silently (which is a common problem with Promises). 

To fix it just do this:

```javascript
    it("provision with illegal bucketname", function(done) {
		lambda.invoke(provisionLambda, JSON.stringify({"bucketName": "3S349'"})).then(function(data) {
			var payload = JSON.parse(data.Payload);
			expect(message.errorType).toBe("InvalidBucketName");
			done();
		}).catch(function(err) {
			console.log(err);
			done();
		});
	});
```
