### ISSUE TITLE
With latest version of jasmine-core 2.6.0, PhantomJS keeps disconnecting without running any specs

### ISSUE THREAD

**Issue by avinashsmiles** [jasmine/jasmine-npm#116] opened 2017-04-27 07:55 UTC
We are recently facing an issue in our build servers where PhantomJS keeps disconnecting. After trying out different things, finally figured out that it happens only with the new version of jasmine-core 2.6.0. If we use version 2.5.2 , there is no issue. So I think something is broken in the update. 

Below is the error we get by using 2.6.0
```
build	26-Apr-2017 09:11:10	[33mWARN [PhantomJS 2.1.1 (Linux)]: [39mDisconnected (1 times), because no message in 10000 ms.
build	26-Apr-2017 09:11:10	PhantomJS 2.1.1 (Linux): Executed 0 of 0[31m DISCONNECTED[39m (10.556 secs / 0 secs)
build	26-Apr-2017 09:11:10	[33mWarning: Task "karma:ci" failed. Use --force to continue.[39m
```

**Comment by slackersoft** [comment] 2017-05-02 21:03
Closing this as a duplicate of jasmine/jasmine#1327

Thanks for using Jasmine!

**Closed by slackersoft** 2017-05-02 21:03 UTC
