### ISSUE TITLE
Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by elijahb** [jasmine/jasmine-npm#119] opened 2017-05-04 11:33 UTC
Hi,
recently installed jasmine 2.6.0, and when running without any test, an error is thrown:

> /home/app/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:2171
>      handler.apply(null, Array.prototype.slice.call(arguments, 0));
>             ^
>
>TypeError: Cannot read property 'apply' of undefined
>    at process.onerror (/home/app/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:2171:14)
>    at emitOne (events.js:96:13)
>    at process.emit (events.js:188:7)
>    at process._fatalException (bootstrap_node.js:297:26)

Downgraded to 2.5.3 and it runs fine. Using Node 6.10.3.

**Comment by slackersoft** [comment] 2017-05-11 20:50
I think this is a duplicate of jasmine/jasmine#1342 and it's ilk. It should be fixed on master of jasmine-core with jasmine/jasmine#1352.

Closing. Thanks for using Jasmine!

**Closed by slackersoft** 2017-05-11 20:50 UTC
